### ISSUE TITLE
No settings.php file for repo

### ISSUE THREAD

**Issue by stpaultim** [backdrop-ops/backdropcms.org#617] opened 2019-12-13 00:09 UTC
Trying to spin up local site for first time and noticing there is no settings.php file for this repo. There is one in both the forum.backdropcms.org the api.backdropcms.org repo. 

I wonder why there is none here. Should there be?

**Comment by stpaultim** [comment] 2019-12-13 00:16
I ran into trouble, because Backdrop was looking for the wrong config directory without settings.php. 

I just copied settings.php from api.backdropcms.org and that worked to get site working.

I'm using Lando.

**Comment by serundeputy** [comment] 2019-12-13 01:10
typically i do not put settings.php in the repo

**Comment by stpaultim** [comment] 2019-12-13 02:37
I could raise the purpose of settings.local.php - but, I won't ;-)

I think that for developing on these sites, with special configuration paths it's helpful to have that provided. 

Also, it seems like consistency between the three infrastructure sites makes sense.

**Comment by jenlampton** [comment] 2019-12-13 21:43
> There is one in both the forum.backdropcms.org the api.backdropcms.org repo. I wonder why there is none here. Should there be?

Yes, there should be one in this repo. 

All our prod instances have a `settings.local.php` file that contains the relevant information for that environment. We did this specifically so that we can have a `settings.php` file in Git that contains all the settings that are necessary for all instances. 

> I ran into trouble, because Backdrop was looking for the wrong config directory without settings.php.

I'm not sure that having the default `settings.php` file would help with this, since the config directory locations for your local site should be defined in your `settings.local.php` file. What's in the default file -- I think -- is what we do on live? 

Maybe we should change that on all repos so it's easier for everyone to get a local site up and running... 

> I think that for developing on these sites, with special configuration paths it's helpful to have that provided.

Ah, perhaps that's what you just said!

**Comment by jenlampton** [comment] 2019-12-13 22:08
> All our prod instances have a settings.local.php file that contains the relevant information for that environment. 

Well, I have confirmed that this is NOT the case for backdropcms.org...

> Also, it seems like consistency between the three infrastructure sites makes sense.

yes, you're right. It definitely should be the same. Fixing now :)

**Comment by jenlampton** [comment] 2019-12-13 23:12
Okay, I think that worked. The live site is still up, anyway. @stpaultim want to rename your `settings.php` file and do a `git pull` to see what happens?

I moved all sensitive info into `settings.local.php` and committed a clean copy of `settings.php` from core, with only a few changes (like setting config dirs to more closely match local dev set-ups.)

**Closed by jenlampton** 2019-12-13 23:12 UTC

**Comment by stpaultim** [comment] 2019-12-14 21:36
Yeah, I think that works better.
