### ISSUE TITLE
Project release node body (auto-imported from GitHub README.md) has html tags and is set to plain text.

### ISSUE THREAD

**Issue by klonos** [backdrop-ops/backdropcms.org#265] opened 2016-06-19 02:17 UTC
Just created my first project release (yay!), but there were a couple of issues: #264 and this one here...

Please take a look at https://backdropcms.org/project/fixteaserlinks to see what I mean. Perhaps it has to do with the fact that when imported from the README.md file, the body of these nodes is set to plain text format. Not sure. ??

**Comment by quicksketch** [comment] 2016-06-20 01:00
This should be fixed now with https://github.com/backdrop-ops/backdropcms.org/commit/c3a8b8c8895d5453cccb6d8cf5f795b3e340bbc9.

This was caused by recently switching the default format for anonymous users to plain_text, which is what the GitHub Project module will use for newly created content. Now we're manually setting this to be the desired text format.

**Closed by quicksketch** 2016-06-20 01:00 UTC
Labels: type - bug

**Comment by klonos** [comment] 2016-06-20 14:02
Yep, that was it. Fixed now! Thanx.
