### ISSUE TITLE
Be consistent with the page title sections across the different pages.

### ISSUE THREAD

**Issue by klonos** [backdrop-ops/backdropcms.org#375] opened 2017-03-29 10:55 UTC
Quickly filing this issue. Screenshots will follow...

- We currently have distinct page title sections (`.l-page-title`) with different background color and "subtitles" for the themes/modules/layouts but in other sections (like the user guide) we do not follow the same pattern.
- The user guide content is narrower than the rest of the site text/content, while its title and primary tabs are wider (not aligned with the main text).
- Unnecessary big gap between the site header (`.l-header`) and the page title section (`.l-page-title`).

**Comment by jenlampton** [comment] 2017-03-31 00:03
> We currently have distinct page title sections (.l-page-title) with different background color and "subtitles" for the themes/modules/layouts but in other sections (like the user guide) we do not follow the same pattern.

This is by design, as those three types of pages are different.  The information displayed here is different, the way users interact with the page is different, generally we need a bit of a different design here. 

The original design had the top part of the page white, and the bottom gray:
![screen shot 2017-03-30 at 4 59 45 pm](https://cloud.githubusercontent.com/assets/397895/24530967/614c2420-156a-11e7-9577-18a1fb287c54.png)

With our new black site header, we decided to reverse that.  I'm not sure flipping the white/gray was the best decision for these pages, and it could certainly use a design review!

Can we please create separate issues for the other two issues? Those are likely bugs :)

**Comment by jenlampton** [comment] 2017-04-07 17:39
I think I have addressed all these issues, closing. (Please open new issues if necessary!)

**Closed by jenlampton** 2017-04-07 17:39 UTC
