### ISSUE TITLE
Showcase Sites Page on backdropcms.org

### ISSUE THREAD

**Issue by JugglingCoder** [backdrop-ops/backdropcms.org#316] opened 2016-11-19 19:19 UTC
I did a search here for "Showcase" and there was a mention of something... but searching all around on backdropcms.org could not find a "Showcase" page so... maybe removed?  I bring this up because recently I suggested to a client I use "Backdrop" (normal I don't tell clients what I use but this particular client was savvy with CMS systems) and he asked, "can you show me some example sites?" and I said... "well... umm... umm..." and couldn't.  I realize this is a "tricky" situation because, to put it bluntly, you don't want to "Showcase" crappy sites and on the other hand you don't want to tell hard working designers/developers, "sorry, your site is not good enough" (LOL).  But... I mean, normal/decent sites built with Backdrop may help to spread the word a bit.

**Comment by serundeputy** [comment] 2016-11-19 19:35
The showcase is not built yet, but this should at least give you some sites to show: https://backdropcms.org/news/built-backdrop-cms

and of course https://backdropcms.org itself is built with Backdrop.

**Comment by klonos** [comment] 2016-11-19 23:23
@JugglingCoder yeah, our official showcase view is not built and published yet (as in the fact that we do not have an easily accessible link in the main site menu for it), but here's the link to it anyways: https://backdropcms.org/showcase

**Comment by klonos** [comment] 2016-12-23 17:39
...lets keep this issue open until we have made public an actual showcase page on b.org.

**Comment by JugglingCoder** [comment] 2016-12-23 17:58
Oh, ok klonos:)  I was just trying to clean up a bit but if you think it should stay open; of course I'll keep it open.

**Comment by klonos** [comment] 2017-04-14 07:11
@JugglingCoder do you have a user account on backdropcms.org? Can you please create one and then create a showcase for www.JapanTravelPackages.com ?

https://backdropcms.org/user/register
https://backdropcms.org/node/add/showcase

**Comment by klonos** [comment] 2017-04-14 07:27
...I will work on getting the Showcase view we already have into a better shape soon as I get some time.

**Comment by klonos** [comment] 2017-04-14 07:56
...for reference, here's what the respective page looks like in d.org:

![image](https://cloud.githubusercontent.com/assets/2423362/25036535/c08918de-2137-11e7-9dbf-11fc964e7ef8.png)

**Comment by klonos** [comment] 2017-04-14 08:16
Played a bit with the view: https://backdropcms.org/showcase

...no styling done yet.

**Comment by JugglingCoder** [comment] 2017-04-14 15:52
I added my JapanTravelPackages.com site to backdropcms.org, thank you klonos.  If your interested in the "look" above "here's what the respective page looks like in d.org"  I use "masonry" (http://masonry.desandro.com/) and imagesloaded (http://imagesloaded.desandro.com/) on my Social Site I built in D7 for photos pages (example: http://www.cloudbrat.com/user/photos/coloradojones) and it works well and was pretty easy to implement.

**Comment by klonos** [comment] 2017-04-15 00:32
Thank you @JugglingCoder 👍 ...I have published the showcase after making some minor edits:

- Changed the "We are a Japan Specialist Travel Company..." in the blurb to "JapanTravelPackages.com is a Japan Specialist Travel Company...". Makes it look more like writing a blog presenting the site rather than posting an ad.
- Changed the "which is a branch of Drupal 7" to "which is based in the code of Drupal 7". Didn't want to use the tech term "fork", and we are not a branch of Drupal either.
- Changed instances of "BackDrop" to "Backdrop" which is the correct spelling/capitalization.
- Removed a few double spaces here and there in the text after full-stops.

I hope you don't mind; in case you do, I've kept a revision that we can revert to. Just let me know  😉 

It is now available in ...

**Comment by klonos** [comment] 2017-04-15 00:37
...keep the Backdrop-based websites coming in 😄

**Comment by JugglingCoder** [comment] 2017-04-15 18:57
The changes you made are no problem.  I actually have another site in Backdrop... http://www.2ptalk.com  (and sister in site in Japanese http://www.chat2shot.com ) but probably don't want it in showcase. 1.) its a "chat" site (half normal chat but half adult oriented chat) and 2.) nobody uses it yet! :)  You should try it once just for fun:)  Use two different browsers and you can chat with yourself... isn't that fun! LOL The "Chat" part is a rather huge custom module I made for Backdrop... it runs so fast!

**Comment by JugglingCoder** [comment] 2017-04-15 19:05
PS which field -> image is used for the "view" ( https://backdropcms.org/showcase )?  Is that the "Hero Photo"? Doesn't seem to be an image for the site in the view.

**Comment by klonos** [comment] 2017-04-15 21:47
@JugglingCoder yes, it's the hero image. You can use a screengrab of the top section of the site on desktop.

**Comment by BWPanda** [comment] 2017-09-28 23:17
Is there some styling missing from the Showcase page? This is what I'm seeing:

![screen shot 2017-09-29 at 09 15 50-fullpage](https://user-images.githubusercontent.com/2385329/30994343-e1281584-a4f6-11e7-9031-ca937cf6ebb0.png)

Also, can anyone with a BD.org account just go and create showcase content, or do we need to get permissions somewhere, or what?

**Comment by jenlampton** [comment] 2017-10-26 19:17
I'm going to close this as a dupe of https://github.com/backdrop-ops/backdropcms.org/issues/176 because as a dev I am confused as to which issue contains the feedback I need.

**Closed by jenlampton** 2017-10-26 19:17 UTC
Labels: type - question
