### ISSUE TITLE
Broken page

### ISSUE THREAD

**Issue by argiepiano** [backdrop-ops/backdropcms.org#913] opened 2022-06-22 13:39 UTC
A search on Google for Backdrop CMS Commerce brings up [this page](https://backdropcms.org/services/e-commerce)  very high in the list. This page seems to be broken.  
<img width="1217" alt="Screen Shot 2022-06-22 at 7 30 26 AM" src="https://user-images.githubusercontent.com/9938978/175043099-93c15de0-d4e3-4948-94c9-96e34e0027cd.png">

**Comment by docwilmot** [comment] 2022-06-22 13:59
It seems `taxonomy/term/%` paths are broken for some vocabs but not others:
https://backdropcms.org/services/hosting
https://backdropcms.org/projects/tags/administration
https://backdropcms.org/features/new-functionality

**Comment by jenlampton** [comment] 2022-07-22 22:25
Well, it's a hotfix for sure, but the page is at least back up:
https://backdropcms.org/services/e-commerce

**Comment by stpaultim** [comment] 2022-12-03 07:49
@jenlampton - Was your hotfix good enough to close this issue or can you better describe what needs to happen?

If the problem isn't visible anymore and we're not sure what your hotfix was, I'm not sure how to proceed with this issue?

**Comment by jenlampton** [comment] 2022-12-06 18:42
@stpaultim  all I did was disable the `Organizations` Layout. I suspect the problem was caused by https://github.com/backdrop/backdrop-issues/issues/5809, which was included in the latest release. I'll try to enable the layout template again after we update core.

**Comment by irinaz** [comment] 2023-06-28 22:32
This issue looks fixed to me :)

**Closed as completed** 2023-06-29 17:46 UTC
