### ISSUE TITLE
Watchdog notifications

### ISSUE THREAD

**Issue by docwilmot** [backdrop-ops/backdropcms.org#756] opened 2021-01-30 00:38 UTC
> Notice: Undefined variable: more in include() (line 30 of /home/backdrop/repo/www/themes/borg/templates/node--project-search.tpl.php)

Hundreds of this in the site logs.

**Comment by BWPanda** [comment] 2021-01-30 09:48
Duplicate of https://github.com/backdrop-contrib/borg/issues/14

**Closed by BWPanda** 2021-01-30 09:48 UTC
