### ISSUE TITLE
Add Docksal to the “try Backdrop” section

### ISSUE THREAD

**Issue by jenlampton** [backdrop-ops/backdropcms.org#599] opened 2019-11-01 00:41 UTC
Add Docksal to the “try Backdrop” section, with steps etc. Add it to the docs/procedures for releases

**Comment by BWPanda** [comment] 2019-11-12 13:54
Duplicate of https://github.com/backdrop-ops/backdropcms.org/issues/586

**Closed** 2019-11-12 13:55 UTC
