### ISSUE TITLE
Add a global search

### ISSUE THREAD

**Issue by goldmantx** [backdrop-ops/backdropcms.org#193] opened 2016-03-11 21:46 UTC
There is no global search on the front page (or anywhere) that I could find on the site. Might be good to plan and implement that.

**Comment by klonos** [comment] 2016-09-02 23:21
The reason why people cannot find the site search is because it is "hidden" inside the *Drawer* region (shown only if people click on the "Handbook" link on the *Sidebar* region = bad discoverability).

There is more issues with that...  the search block is at the bottom of *all* the handbook links (scrolling = bad UX) AND the "search" button is cut in half:

![backdropcms org-issue193-search_block_hidden_inside_drawer_region_and_search_button_cut_in_half](https://cloud.githubusercontent.com/assets/2423362/18220689/d9287a86-71b7-11e6-8f7b-197865e381b1.png)

**Comment by klonos** [comment] 2016-09-02 23:37
Possible solutions:

1. Correct the CSS so that the search button is fully within view port. That's the easy fix, but does not solve the discoverability and usability issues.

2. Move the search block above the handbook menu:

![backdropcms org-issue193-search_block_moved_above_the_handbook_menu](https://cloud.githubusercontent.com/assets/2423362/18220773/c4ddace4-71b8-11e6-85ee-0ee9a0426d09.png)

This would also be an easy fix, would solve the half button issue and the UX issue (less scrolling), but not the discoverability issue.

3. Move the search block from the drawer to the sidebar. That I believe would solve all issues, but would require some additional work on the styling. Here's the two options we have (bellow/above the main menu):

![backdropcms org-issue193-search_block_moved_in_the_sidebar-above-bellow_options_side_by_side](https://cloud.githubusercontent.com/assets/2423362/18220902/fd029e62-71b9-11e6-9eb3-49c35a9feb56.png)

**Comment by klonos** [comment] 2016-09-02 23:42
I personally like the one with the search block on top, but either way, the search button will need some love. Perhaps even merge it with the search field in order to save vertical space?

**Comment by klonos** [comment] 2016-09-03 00:33
...something like this perhaps?:

![backdropcms org-issue193-search_block_moved_to_sidebar](https://cloud.githubusercontent.com/assets/2423362/18221525/dd503798-71c1-11e6-988a-abf9ce66aec6.png)

**Comment by BWPanda** [comment] 2020-05-19 06:01
Since this issue mostly discusses the old design, and since adding global search isn't as simple as just adding a search box to the site (paraphrased quote from linked issue), I'm going to mark this issue as a duplicate of https://github.com/backdrop-ops/backdropcms.org/issues/370

**Closed by BWPanda** 2020-05-19 06:01 UTC
Labels: type - bug, type - task
