### ISSUE TITLE
Fix project releases

### ISSUE THREAD

**Issue by docwilmot** [backdrop-ops/backdropcms.org#70] opened 2015-06-04 14:27 UTC
Hopscotch module has a release on GitHub https://github.com/backdrop-contrib/hopscotch/releases/tag/1.x-1.0. No errors

The releases feed from dev.backdropcms lists "comment_notify" though, as the release name. https://updates.backdropcms.org/release-history/hopscotch/1.x

The Hopscotch project node lists "autofloat" as the release https://dev.backdropcms.org/node/169

The release tab says "no releases". https://dev.backdropcms.org/node/169/releases

I'm hoping that this is leftover from early testing? If not, seems its all messed up. 

@quicksketch

**Comment by quicksketch** [comment] 2015-06-04 17:35
Agreed, there's something weird going on with associating new releases with their parent projects. We'll need to find the underlying bug in project_github.module (the most likely place at least) and also update the database entries to point to their proper projects.

**Comment by docwilmot** [comment] 2015-08-17 01:52
This not fixed. Release nodes still all over the place.

**Comment by quicksketch** [comment] 2015-08-21 04:13
I tracked down the source of this problem. In `project_github.pages.inc` there is this bit of code:

```php
  // Check that we're not about to overwrite an existing node. We will update
  // the existing node with the same version string if applicable.
  $existing_nid = db_query("SELECT nid FROM {project_release} WHERE version = :version", array(':version' => $payload['release']['tag_name']))->fetchField();
  if ($existing_nid) {
    $node = node_load($existing_nid);
  }
```

Even without context, you may be able to see what the problem is. Doing a query where the only condition is "version", means that when two people make a project with the same version (e.g. 1.1.1), then the first project's release is updated to point at the second project's new archives. :stuck_out_tongue: 

Clearly that's all messed up. The bad news is this means that we've got a bunch of releases that are missing. The good news is that the entirety of the project information was updated. Only the title is untouched. This means that as far as update-status is concerned, we're delivering accurate information to client sites (that is, a download link for project_a won't show up if you've installed project_b). The flip side of that however is that there a bunch of released project that might not be sending out update notifications (or collecting statistics). Fortunately, we can recreate all these releases once this bug is fixed.

**Comment by docwilmot** [comment] 2015-08-21 04:19
Great. Was delaying releasing till this was fixed; will start once you give the all clear.

**Comment by quicksketch** [comment] 2015-08-21 04:21
Just pushed the fix: https://github.com/backdrop-ops/backdropcms.org/commit/c24b6f413fec593c71222dfece1e3dba4b7f3ec2

I'll fix this in project module in https://github.com/backdrop-contrib/project/issues/5

**Comment by quicksketch** [comment] 2015-08-21 04:21
Could you publish your new release when you get the chance? It's a straight-forward fix but it would be great to see it in action.

**Comment by docwilmot** [comment] 2015-08-21 04:25
Yep, all good: https://backdropcms.org/project/hopscotch

**Comment by quicksketch** [comment] 2015-08-21 04:28
Nice! I want to leave this issue open though until we recreate all the missing releases. I'll work on making an update function to retrieve all the projects from GitHub and recreate the missing ones.

**Comment by quicksketch** [comment] 2015-08-22 03:51
Fixed in https://github.com/backdrop-ops/backdropcms.org/commit/bfc7bdc3d0b38702c91155a7c55055c2a0d18cea. I've run the update on the production site and now we've got all our releases properly in place for all modules. That created almost 50 new release nodes! It's good to have this fixed. I'll make a new release of Project module shortly that includes these fixes.

**Closed by quicksketch** 2015-08-22 03:51 UTC
Labels: type - bug
