### ISSUE TITLE
Access denied if clicked on "See all versions >" on project page

### ISSUE THREAD

**Issue by ghost** [backdrop-ops/backdropcms.org#398] opened 2017-06-15 10:30 UTC
Cannot access the page if clicked on "See all versions >" on a project page.

**Comment by jenlampton** [comment] 2017-08-11 19:38
I'm unable to reproduce this problem, but we did just make some changes to the releases page not too long ago. Can you please confirm this is still an issue for you? If so I will look into it further.

**Comment by BWPanda** [comment] 2022-07-06 08:43
I can't replicate either as an anonymous user. Closing.

**Closed by BWPanda** 2022-07-06 08:43 UTC
Labels: needs - more feedback
