### ISSUE TITLE
Docs: Accomodate for contrib projects documentation in b.org

### ISSUE THREAD

**Issue by klonos** [backdrop-ops/backdropcms.org#462] opened 2018-07-23 23:48 UTC
In d.org, there used to be "documentation" links on the right sidebar for contrib projects, and that documentation was hosted within d.org.

Our current docs in Support > User guide (https://backdropcms.org/user-guide) is for core docs (with a separate external link item for the API docs). For contrib projects, we do have a "Documentation" link that points to GitHub, but do we want GitHub to be the source of docs?:

a) is it user-friendly?
b) is it easy for people other than the contrib project authors to contribute to docs?
c) does it look good that documentation is "scattered" in two different places?
d) could we benefit from SEO/traffic if the documentation was hosted in b.org instead?

Let discuss the above. The easy solution is to leave things as they are of course.

**Comment by BWPanda** [comment] 2021-01-15 20:28
@klonos Is this a duplicate of https://github.com/backdrop-ops/backdropcms.org/issues/627 ?

**Comment by BWPanda** [comment] 2021-06-09 21:57
Going to close this as a duplicate. Also, a lot's changed since Greg's comment, so if this isn't a duplicate then perhaps a new issue would be best anyway.

**Closed by BWPanda** 2021-06-09 21:57 UTC
Labels: type - question, type - task
