### ISSUE TITLE
Link to GitHub project page, issues and documentation from module/theme/layout page.

### ISSUE THREAD

**Issue by klonos** [backdrop-ops/backdropcms.org#86] opened 2015-08-16 04:58 UTC
I was testing https://backdropcms.org/modules and https://backdropcms.org/themes and was looking for a link that pointed to the respective repo in GitHub, but nothing.

People can get the latest release because we have a link to it already and they can also get the info because we pull and display the contents of the README.md files, but no way to see previous all releases or find a place to file issues.

**Comment by klonos** [comment] 2015-08-16 04:59
...also OT, but are we good to get links to the modules and themes pages to the main site menu at backdropcms.org or not yet?

**Comment by sutibun** [comment] 2015-10-24 21:50
+1

I didn't even know the video filter module was ported. Not until I checked the contrib modules in Github. I'd be happy even if the link was on the bottom of their respective page.

**Comment by jenlampton** [comment] 2016-01-29 04:45
Yep, its in the designs. We just don't have the actual data to display just yet. Marking this as a dupe of https://github.com/backdrop-ops/backdropcms.org/issues/95

**Comment by klonos** [comment] 2016-01-31 10:08
...actually, let's keep this issue here open as the other issue is a meta and this a sub-task of it.

**Comment by klonos** [comment] 2016-01-31 10:10
...better title as this is to add an entire "GitHub" block in each project page that (according to current design at the time of writing) is meant to add 3 links to GitHub: project, issues and documentation

**Comment by jenlampton** [comment] 2016-02-01 00:43
thanks :)

**Comment by BWPanda** [comment] 2016-05-18 01:53
:+1: Yes please!

**Comment by stpaultim** [comment] 2019-11-10 00:24
Actually, it looks to me like this task is complete. I'll leave it open for a few more days in case I'm missing anything, but unless someone expresses the need to keep this open, I'll close it next time through these issues (I expect in a few days). 

![Search_Index_Options___Backdrop_CMS](https://user-images.githubusercontent.com/3144571/68536782-ea6a6e80-031d-11ea-8913-0451a8bc1abf.png)

**Comment by BWPanda** [comment] 2022-07-07 08:58
A few days later with no objections... Let's close 😉

**Closed by BWPanda** 2022-07-07 08:58 UTC
